##### Config for the `infer_det.py` hack. Adapted from ch_PP-OCRv3_det_cml_teacheronly_synthdog2000.yml
Global:
  debug: false
  use_gpu: true
  pretrained_model: ~/.paddleocr/whl/det/en/ch_PP-OCRv3_det_cml_teacheronly_synthdog2000/iter_epoch_1

Architecture:
  model_type: det
  algorithm: DB
  Backbone:
    name: ResNet
    in_channels: 3
    layers: 50
  Neck:
    name: LKPAN
    out_channels: 256
  Head:
    name: DBHead
    kernel_list: [7,2,2]
    k: 50

PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

Eval:
  dataset:
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - DetResizeForTest: null
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
